// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbP3__b4G7NLYrRqfIUD3NiTnVvauW4nI',
    appId: '1:685203300793:web:c28e59624d9292f8b41668',
    messagingSenderId: '685203300793',
    projectId: 'lactoguard-ai',
    authDomain: 'lactoguard-ai.firebaseapp.com',
    storageBucket: 'lactoguard-ai.firebasestorage.app',
    measurementId: 'G-Q8J88JFG7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-1Z1ytHAThpm2VX4rq0WrRXbC2nw1vgM',
    appId: '1:685203300793:android:ae0889e86372e533b41668',
    messagingSenderId: '685203300793',
    projectId: 'lactoguard-ai',
    storageBucket: 'lactoguard-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ6K3RdwupfTxRd_43xeDhZks9WCTPtsc',
    appId: '1:685203300793:ios:2ec42b7cdde573d3b41668',
    messagingSenderId: '685203300793',
    projectId: 'lactoguard-ai',
    storageBucket: 'lactoguard-ai.firebasestorage.app',
    iosBundleId: 'com.example.lactoguardAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ6K3RdwupfTxRd_43xeDhZks9WCTPtsc',
    appId: '1:685203300793:ios:2ec42b7cdde573d3b41668',
    messagingSenderId: '685203300793',
    projectId: 'lactoguard-ai',
    storageBucket: 'lactoguard-ai.firebasestorage.app',
    iosBundleId: 'com.example.lactoguardAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbP3__b4G7NLYrRqfIUD3NiTnVvauW4nI',
    appId: '1:685203300793:web:4a96912e127d8e4fb41668',
    messagingSenderId: '685203300793',
    projectId: 'lactoguard-ai',
    authDomain: 'lactoguard-ai.firebaseapp.com',
    storageBucket: 'lactoguard-ai.firebasestorage.app',
    measurementId: 'G-P6R4117C35',
  );
}
